global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'shop-dev-prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'shop-dev-api'
    scrape_interval: 5s
    static_configs:
      - targets: ['app:8002']
