server:
  port: 8002
  mode: "dev"

mysql:
  host: mysql_container
  port: 3306
  username: root
  password: root1234
  dbname: shopdevgo
  maxIdleConns: 10  #so luong ket noi idle toi da
  maxOpenConns: 100 # so luong ket noi open toi da
  connMaxLifetime: 3600 # thoi gian toi da cua ket noi

logger:
  log_level: debug
  file_log_name: "./storage/logs/app.log"
  max_size: 500
  max_backups: 3
  max_age: 28
  compress: true

redis:
  host: redis_container
  port: 6379
  password: ""
  database: 0

jwt:
  token_hour_lifespan: 1
  jwt_expiration: 1h
  api_secret_key: "127.0.0.1"